const FETCH_POST_BEGIN = "FETCH_POST_BEGIN";
const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
const FETCH_POST_ERROR = "FETCH_POST_ERROR";

export { FETCH_POST_BEGIN, FETCH_POST_SUCCESS, FETCH_POST_ERROR };
